# Generated by Django 5.0.6 on 2026-09-27 04:47

import django.core.validators
import django.db.models.deletion
import mobilewash.models
import mobilewash.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "legal_name",
                    models.CharField(max_length=220, verbose_name="Raison sociale"),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="Nom commercial"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "commune",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Commune"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Kinshasa", max_length=120, verbose_name="Ville"
                    ),
                ),
                (
                    "rccm",
                    models.CharField(blank=True, max_length=80, verbose_name="RCCM"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Numero d'impot"
                    ),
                ),
                (
                    "id_nat",
                    models.CharField(blank=True, max_length=80, verbose_name="ID NAT"),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email facturation"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Telephone"
                    ),
                ),
                (
                    "default_payment_terms_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Delai paiement"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
            ],
            options={
                "verbose_name": "Entreprise corporate",
                "verbose_name_plural": "Entreprises corporate",
                "ordering": ["legal_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "legal_name"],
                        name="mobilewash__is_acti_73778e_idx",
                    ),
                    models.Index(
                        fields=["city", "commune"], name="mobilewash__city_f25145_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Numero contrat"
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="Titre")),
                ("start_date", models.DateField(verbose_name="Date debut")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENT", "Envoye"),
                            ("NEGOTIATING", "Negociation"),
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                            ("EXPIRED", "Expire"),
                            ("TERMINATED", "Termine"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Mensuelle")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "monthly_package_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("360.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("included_washes_per_month", models.PositiveIntegerField(default=12)),
                ("included_visits_per_month", models.PositiveIntegerField(default=0)),
                (
                    "additional_wash_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_vehicles_per_intervention",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "minimum_intervention_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                ("service_location", models.TextField(verbose_name="Lieu de service")),
                (
                    "default_service_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Lavage standard"),
                            ("EXTERIOR", "Exterieur"),
                            ("COMPLETE", "Complet"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("default_team_size", models.PositiveSmallIntegerField(default=2)),
                ("client_obligations", models.TextField(blank=True)),
                ("shine_obligations", models.TextField(blank=True)),
                ("cancellation_notice", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "signed_contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mobilewash.models.signed_contract_upload_path,
                        validators=[mobilewash.validators.validate_mobile_file],
                    ),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_contracts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="mobilewash.corporatecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat mobile",
                "verbose_name_plural": "Contrats mobiles",
                "ordering": ["-start_date", "contract_number"],
                "permissions": [
                    (
                        "view_mobile_financials",
                        "Voir les donnees financieres lavage mobile",
                    ),
                    ("approve_mobile_contract", "Approuver les contrats lavage mobile"),
                    (
                        "override_workorder_review",
                        "Finaliser un ordre sans revue manager",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CorporateContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Contact principal"),
                            ("OPS", "Contact operationnel"),
                            ("AP", "Comptabilite fournisseur"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="Nom complet"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Fonction"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Telephone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="mobilewash.corporatecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact corporate",
                "verbose_name_plural": "Contacts corporate",
                "ordering": ["company", "role", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="MobileEmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "Manager"),
                            ("LEAD_WASHER", "Chef laveur"),
                            ("MOBILE_WASHER", "Laveur mobile"),
                            ("SUPPORT_WASHER", "Support laveur"),
                        ],
                        default="MOBILE_WASHER",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("quality_issues", models.PositiveIntegerField(default=0)),
                ("rewash_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobilewash_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employe lavage mobile",
                "verbose_name_plural": "Employes lavage mobile",
            },
        ),
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                ("service_location", models.TextField()),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("planned_start_time", models.TimeField()),
                ("planned_duration_minutes", models.PositiveIntegerField(default=120)),
                ("planned_vehicles", models.PositiveIntegerField(default=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="mobilewash.corporatecompany",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="mobilewash.contract",
                    ),
                ),
                (
                    "default_assigned_team",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mobile_default_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme recurrent mobile",
                "verbose_name_plural": "Programmes recurrents mobiles",
                "ordering": ["weekday", "planned_start_time"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                ("internal_fleet_number", models.CharField(blank=True, max_length=80)),
                ("license_plate", models.CharField(blank=True, max_length=60)),
                ("vehicle_type", models.CharField(blank=True, max_length=80)),
                ("make", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("color", models.CharField(blank=True, max_length=60)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="mobilewash.corporatecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicule corporate",
                "verbose_name_plural": "Vehicules corporate",
                "ordering": ["company", "license_plate", "internal_fleet_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "work_order_number",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                ("service_location", models.TextField()),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("planned_duration_minutes", models.PositiveIntegerField(default=120)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("planned_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "price_classification",
                    models.CharField(
                        choices=[
                            ("INCLUDED", "Inclus contrat"),
                            ("ADDITIONAL", "Supplementaire"),
                            ("SPECIAL", "Service special"),
                        ],
                        default="INCLUDED",
                        max_length=20,
                    ),
                ),
                (
                    "client_representative_name",
                    models.CharField(blank=True, max_length=160),
                ),
                (
                    "client_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mobilewash.models.signature_upload_path,
                        validators=[mobilewash.validators.validate_mobile_image],
                    ),
                ),
                ("client_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("associate_name", models.CharField(blank=True, max_length=160)),
                (
                    "associate_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mobilewash.models.signature_upload_path,
                        validators=[mobilewash.validators.validate_mobile_image],
                    ),
                ),
                ("associate_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("no_access_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Planifie"),
                            ("DISPATCHED", "Equipe envoyee"),
                            ("IN_PROGRESS", "En cours"),
                            ("AWAITING_CONFIRMATION", "Attente confirmation client"),
                            ("SUBMITTED", "Soumis pour revue"),
                            ("COMPLETED", "Termine"),
                            ("CANCELLED", "Annule"),
                            ("NO_ACCESS", "Acces impossible"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=30,
                    ),
                ),
                (
                    "machine_fuel_litres",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "machine_fuel_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "soap_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "perfume_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "water_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "other_consumables_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "equipment_maintenance_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mobile_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="mobilewash.corporatecompany",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="mobilewash.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_work_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_work_orders_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="mobilewash.recurringschedule",
                    ),
                ),
                (
                    "team_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_work_orders_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre de travail mobile",
                "verbose_name_plural": "Ordres de travail mobiles",
                "ordering": ["-scheduled_start", "work_order_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProofPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=mobilewash.models.proof_upload_path,
                        validators=[mobilewash.validators.validate_mobile_image],
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Avant"),
                            ("AFTER", "Apres"),
                            ("SIGNATURE", "Signature"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_photos",
                        to="mobilewash.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve photo mobile",
                "verbose_name_plural": "Preuves photo mobiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                ("license_plate_snapshot", models.CharField(blank=True, max_length=60)),
                ("service_type", models.CharField(default="STANDARD", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "A faire"),
                            ("COMPLETED", "Termine"),
                            ("SKIPPED", "Non lave"),
                            ("REWASH", "Relavage"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "before_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mobilewash.models.proof_upload_path,
                        validators=[mobilewash.validators.validate_mobile_image],
                    ),
                ),
                (
                    "after_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mobilewash.models.proof_upload_path,
                        validators=[mobilewash.validators.validate_mobile_image],
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_lines",
                        to="mobilewash.vehicle",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_lines",
                        to="mobilewash.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicule lave sur ordre",
                "verbose_name_plural": "Vehicules laves sur ordre",
                "ordering": ["work_order", "license_plate_snapshot", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["company", "status"], name="mobilewash__company_8df9d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["status", "start_date"], name="mobilewash__status_90d6aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["contract_number"], name="mobilewash__contrac_72ccc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporatecontact",
            index=models.Index(
                fields=["company", "role", "is_active"],
                name="mobilewash__company_d45030_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mobileemployeeprofile",
            index=models.Index(
                fields=["role", "is_active"], name="mobilewash__role_8394cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringschedule",
            index=models.Index(
                fields=["company", "is_active"], name="mobilewash__company_5f32ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringschedule",
            index=models.Index(
                fields=["contract", "is_active"], name="mobilewash__contrac_2ad965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringschedule",
            index=models.Index(
                fields=["weekday", "is_active"], name="mobilewash__weekday_dd69f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["company", "is_active"], name="mobilewash__company_7444a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="mobilewash__license_a0d4fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True), models.Q(("license_plate", ""), _negated=True)
                ),
                fields=("company", "license_plate"),
                name="mobilewash_unique_active_plate_company",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["company", "status"], name="mobilewash__company_6a665a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["contract", "status"], name="mobilewash__contrac_513806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["scheduled_start", "status"],
                name="mobilewash__schedul_3ff1bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "reviewed_at"], name="mobilewash__status_87e616_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("schedule", "scheduled_start"),
                name="mobilewash_one_workorder_per_schedule_visit",
            ),
        ),
        migrations.AddIndex(
            model_name="workordervehicle",
            index=models.Index(
                fields=["work_order", "status"], name="mobilewash__work_or_64e8e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workordervehicle",
            index=models.Index(
                fields=["vehicle", "status"], name="mobilewash__vehicle_a1c434_idx"
            ),
        ),
    ]
