# Generated by Django 5.0.6 on 2026-01-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQRToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("nonce", models.CharField(max_length=32, verbose_name="Nonce")),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Token"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "regenerated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Régénéré le"
                    ),
                ),
                (
                    "regenerated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_regenerations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Régénéré par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Token du Jour",
                "verbose_name_plural": "QR Tokens du Jour",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("clock_in_time", models.DateTimeField(verbose_name="Heure d'entrée")),
                (
                    "clock_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de sortie"
                    ),
                ),
                (
                    "daily_report_confirmed",
                    models.BooleanField(default=False, verbose_name="Rapport confirmé"),
                ),
                (
                    "total_lavages_reported",
                    models.IntegerField(
                        default=0, verbose_name="Total lavages déclaré"
                    ),
                ),
                (
                    "correction_reason",
                    models.TextField(blank=True, verbose_name="Motif de correction"),
                ),
                (
                    "corrected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Corrigé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "clock_in_qr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clock_ins",
                        to="pointage.dailyqrtoken",
                        verbose_name="QR Entrée",
                    ),
                ),
                (
                    "clock_out_qr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clock_outs",
                        to="pointage.dailyqrtoken",
                        verbose_name="QR Sortie",
                    ),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pointages_corriges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Corrigé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "ordering": ["-date", "-clock_in_time"],
            },
        ),
        migrations.AddIndex(
            model_name="dailyqrtoken",
            index=models.Index(
                fields=["site", "date", "actif"], name="pointage_da_site_id_8fc4c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyqrtoken",
            index=models.Index(fields=["token"], name="pointage_da_token_543c94_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyqrtoken",
            unique_together={("site", "date", "actif")},
        ),
        migrations.AddIndex(
            model_name="shiftday",
            index=models.Index(
                fields=["employe", "date"], name="pointage_sh_employe_ffb276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftday",
            index=models.Index(
                fields=["site", "date"], name="pointage_sh_site_id_69063c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftday",
            unique_together={("employe", "date")},
        ),
    ]
