# Generated by Django 5.0.6 on 2026-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftday",
            name="clock_in_qr",
        ),
        migrations.RemoveField(
            model_name="shiftday",
            name="clock_out_qr",
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_gps_distance_mètres",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Distance GPS (entrée, mètres)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_gps_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude GPS (entrée)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_gps_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude GPS (entrée)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_gps_status",
            field=models.CharField(
                choices=[
                    ("OK", "OK"),
                    ("HORS_ZONE", "Hors zone"),
                    ("INCONNU", "Inconnu"),
                ],
                default="INCONNU",
                max_length=20,
                verbose_name="Statut GPS (entrée)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_gps_distance_mètres",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Distance GPS (sortie, mètres)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_gps_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude GPS (sortie)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_gps_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude GPS (sortie)",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_gps_status",
            field=models.CharField(
                choices=[
                    ("OK", "OK"),
                    ("HORS_ZONE", "Hors zone"),
                    ("INCONNU", "Inconnu"),
                ],
                default="INCONNU",
                max_length=20,
                verbose_name="Statut GPS (sortie)",
            ),
        ),
        migrations.AlterField(
            model_name="shiftday",
            name="clock_in_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Heure d'entrée"
            ),
        ),
    ]
