# Generated by Django 5.0.6 on 2026-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0002_remove_shiftday_clock_in_qr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftday",
            name="lavages_review",
            field=models.TextField(blank=True, verbose_name="Revue des lavages"),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="problems_review",
            field=models.TextField(blank=True, verbose_name="Revue des problèmes"),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="report_notes",
            field=models.TextField(blank=True, verbose_name="Notes du rapport"),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="total_amount_reported_fc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Montant total déclaré (FC)",
            ),
        ),
    ]
