# Generated by Django 5.0.6 on 2026-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0003_shiftday_lavages_review_shiftday_problems_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftday",
            name="daily_expenses",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Depenses du jour"
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="daily_expenses_total_fc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total depenses du jour (FC)",
            ),
        ),
    ]
