# Generated by Django 5.0.6 on 2026-06-30 23:14

import pointage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0005_shiftday_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pointage.models.attendance_photo_path,
                verbose_name="Photo de début de journée",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_in_photo_taken_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Photo entrée prise à"
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pointage.models.attendance_photo_path,
                verbose_name="Photo de fin de journée",
            ),
        ),
        migrations.AddField(
            model_name="shiftday",
            name="clock_out_photo_taken_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Photo sortie prise à"
            ),
        ),
    ]
