# Generated by Django 5.0.6 on 2026-08-15 16:18

import django.db.models.deletion
import pointage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0006_shiftday_clock_in_photo_and_more"),
        ("sites", "0025_sitedocument_site_doc_site_uploaded_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerEquipmentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_name",
                    models.CharField(max_length=200, verbose_name="Nom de la machine"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=pointage.models.manager_equipment_photo_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Prise à"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_photos",
                        to="pointage.shiftday",
                        verbose_name="Rapport manager",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_equipment_photos",
                        to="sites.managermanualmachine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_equipment_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo équipement manager",
                "verbose_name_plural": "Photos équipements manager",
                "ordering": ["daily_report__date", "machine_name", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["daily_report", "machine"],
                        name="mgr_equip_report_machine_idx",
                    ),
                    models.Index(fields=["uploaded_at"], name="mgr_equip_uploaded_idx"),
                ],
            },
        ),
    ]
