# Generated by Django 5.0.6 on 2026-01-27 05:49

import django.core.validators
import django.db.models.deletion
import lavages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarWash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "type_service",
                    models.CharField(
                        choices=[
                            ("COMPLET", "Lavage Complet"),
                            ("EXTERIEUR", "Lavage Extérieur"),
                            ("INTERIEUR", "Lavage Intérieur"),
                            ("EXPRESS", "Lavage Express"),
                            ("PREMIUM", "Lavage Premium"),
                        ],
                        default="COMPLET",
                        max_length=20,
                        verbose_name="Type de service",
                    ),
                ),
                (
                    "plaque",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de plaque"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant payé (FC)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lavages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lavage",
                "verbose_name_plural": "Lavages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarWashPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=lavages.models.carwash_photo_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "type_photo",
                    models.CharField(
                        choices=[
                            ("AVANT", "Avant"),
                            ("APRES", "Après"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                        verbose_name="Type de photo",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadé le"),
                ),
                (
                    "lavage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="lavages.carwash",
                        verbose_name="Lavage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo de Lavage",
                "verbose_name_plural": "Photos de Lavage",
                "ordering": ["type_photo", "uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="carwash",
            index=models.Index(
                fields=["employe", "date"], name="lavages_car_employe_e28f16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carwash",
            index=models.Index(
                fields=["site", "date"], name="lavages_car_site_id_a68c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carwash",
            index=models.Index(
                fields=["-created_at"], name="lavages_car_created_39d6f2_idx"
            ),
        ),
    ]
