# Generated by Django 5.0.6 on 2026-03-03 11:38

import lavages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lavages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwash",
            name="plaque_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lavages.models.plaque_photo_path,
                verbose_name="Photo de la plaque",
            ),
        ),
    ]
