# Generated by Django 5.0.6 on 2026-05-12 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lavages", "0002_carwash_plaque_photo"),
        ("sites", "0012_dailybankdeposit_is_system_generated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carwash",
            name="is_system_generated",
            field=models.BooleanField(
                default=False, verbose_name="Généré automatiquement"
            ),
        ),
        migrations.AddField(
            model_name="carwash",
            name="system_source",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Source système"
            ),
        ),
        migrations.AddIndex(
            model_name="carwash",
            index=models.Index(
                fields=["is_system_generated", "system_source"],
                name="lavages_car_is_syst_cd59b7_idx",
            ),
        ),
    ]
