"""
Django settings for shinecongo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-q+obmrtt7uw1k!r2(y^+5iz#-&zc)2__lh(+w=r*9!(%s*$tqg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    # "rest_framework",  # Commented out - not installed
    # "corsheaders",  # Commented out - not installed
    # "storages",  # For AWS S3 storage - only add if USE_S3=True and module installed
    
    # Custom apps
    "comptes",
    "sites",
    "pointage",
    "lavages",
    "problemes",
    "audit",
]

# Check if S3 should be used and if storages module is available
USE_S3_ENV = os.getenv('USE_S3', 'False') == 'True'
USE_S3 = False

if USE_S3_ENV:
    try:
        import storages
        INSTALLED_APPS.append('storages')
        USE_S3 = True
    except (ImportError, ModuleNotFoundError):
        USE_S3 = False
        import warnings
        warnings.warn("⚠️  django-storages not installed. S3 storage disabled. Install with: pip install django-storages boto3")

MIDDLEWARE = [
    # "corsheaders.middleware.CorsMiddleware",  # Commented out - not installed
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "shinecongo.middleware.NoCacheMiddleware",
]

ROOT_URLCONF = "shinecongo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "shinecongo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
# Validation simplifiée : seulement 4 caractères minimum

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 4,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Kinshasa"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# AWS S3 Configuration (USE_S3 is set above, check if storages is available)
if USE_S3:
    try:
        # First check if storages module is available
        import storages
        # Then try to import our custom storage backends
        from storages_backends import StaticStorage, MediaStorage
        
        # AWS settings
        AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
        AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
        AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_DEFAULT_ACL = 'public-read'
        
        # Static files
        STATICFILES_STORAGE = 'storages_backends.StaticStorage'
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
        
        # Media files
        DEFAULT_FILE_STORAGE = 'storages_backends.MediaStorage'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
        
        # S3 settings
        AWS_S3_OBJECT_PARAMETERS = {
            'CacheControl': 'max-age=86400',
        }
        AWS_LOCATION = ''
        AWS_QUERYSTRING_AUTH = False
    except (ImportError, ModuleNotFoundError) as e:
        # Fallback to local storage if storages_backends not available
        USE_S3 = False
        STATIC_URL = "static/"
        STATICFILES_DIRS = [BASE_DIR / "static"]
        STATIC_ROOT = BASE_DIR / "staticfiles"
        MEDIA_URL = "media/"
        MEDIA_ROOT = BASE_DIR / "media"
        import warnings
        warnings.warn(f"S3 storage disabled: {e}. Install with: pip install django-storages boto3")
else:
    # Local development
    STATIC_URL = "static/"
    STATICFILES_DIRS = [BASE_DIR / "static"]
    STATIC_ROOT = BASE_DIR / "staticfiles"
    
    # Media files (user uploads)
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication URLs
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# QR Code Security
QR_SECRET_KEY = os.getenv("DJANGO_SECRET_QR", "changeme-in-production-qr-secret-key")

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# CORS settings (for API if needed)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
