# Generated by Django 5.0.6 on 2026-01-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREER", "Créer"),
                            ("MODIFIER", "Modifier"),
                            ("SUPPRIMER", "Supprimer"),
                            ("CORRIGER_POINTAGE", "Corriger Pointage"),
                            ("REGENERER_QR", "Régénérer QR"),
                            ("CHANGER_STATUT", "Changer Statut"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de l'objet"
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant"
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée d'Audit",
                "verbose_name_plural": "Journal d'Audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_audit_user_id_429f6b_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_6e540c_idx"
                    ),
                ],
            },
        ),
    ]
