# Generated by Django 5.0.6 on 2026-03-03 22:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0001_initial"),
        ("sites", "0005_sitedocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_embauche",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'embauche"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mpesa_numero",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Numéro M-Pesa"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salaire_mensuel_fc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salaire mensuel (FC)",
            ),
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de paiement",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Période du")),
                ("period_end", models.DateField(verbose_name="Période au")),
                (
                    "salary_base_fc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salaire de base (FC)",
                    ),
                ),
                (
                    "amount_paid_fc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant payé (FC)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("ESPECES", "Espèces"),
                            ("BANQUE", "Virement bancaire"),
                        ],
                        default="MPESA",
                        max_length=15,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "mpesa_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence M-Pesa"
                    ),
                ),
                (
                    "employee_signature_name",
                    models.CharField(
                        max_length=150, verbose_name="Signature employé (nom)"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Signé le"
                    ),
                ),
                (
                    "admin_signature_name",
                    models.CharField(max_length=150, verbose_name="Signature admin"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_payments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="comptes.userprofile",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_payments",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Employé",
                "verbose_name_plural": "Paiements Employés",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "payment_date"],
                        name="comptes_emp_site_id_d88546_idx",
                    ),
                    models.Index(
                        fields=["employee_profile", "payment_date"],
                        name="comptes_emp_employe_8b149f_idx",
                    ),
                ],
            },
        ),
    ]
