# Generated by Django 5.0.6 on 2026-03-03 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_userprofile_date_embauche_userprofile_mpesa_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeepayment",
            name="amount_paid_fc",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant payé (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="employeepayment",
            name="salary_base_fc",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salaire de base (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="salaire_mensuel_fc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salaire mensuel (USD)",
            ),
        ),
    ]
