# Generated by Django 5.0.6 on 2026-03-05 22:41

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0004_rename_payroll_fields_to_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=comptes.models.employee_cv_upload_path,
                verbose_name="CV employé",
            ),
        ),
    ]
