# Generated by Django 5.0.6 on 2026-03-05 22:54

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0005_userprofile_cv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=comptes.models.employee_photo_upload_path,
                verbose_name="Photo employé",
            ),
        ),
    ]
