# Generated by Django 5.0.6 on 2026-05-19 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0007_userprofile_admin_inbox_seen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.CreateModel(
            name="AdminReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("PORTAL", "Portail"),
                            ("WEBSITE", "Site web shinecongo.org"),
                        ],
                        default="PORTAL",
                        max_length=20,
                        verbose_name="Cible",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("IMPORTANT", "Important"),
                            ("URGENT", "Urgent"),
                        ],
                        default="IMPORTANT",
                        max_length=12,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optionnel. Utilisez-le pour faire remonter un rappel à une date précise.",
                        null=True,
                        verbose_name="Échéance",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_reminders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rappel Admin",
                "verbose_name_plural": "Rappels Admin",
                "ordering": ["is_resolved", "due_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "due_at"],
                        name="comptes_adm_is_reso_119c35_idx",
                    ),
                    models.Index(
                        fields=["target", "priority"],
                        name="comptes_adm_target_a3d0e5_idx",
                    ),
                ],
            },
        ),
    ]
