# Generated by Django 5.0.6 on 2026-05-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0008_userprofile_date_naissance_adminreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admin_messages_last_seen_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Dernière consultation des messages admin",
            ),
        ),
    ]
