# Generated by Django 5.0.6 on 2026-05-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0009_userprofile_admin_messages_last_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("EMPLOYE", "Employé"),
                    ("CONTROLE_CAMERA", "Contrôle caméra"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Administrateur"),
                ],
                default="EMPLOYE",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
