from django.urls import path

from .views import (
    EmployeeCarWashDetailApi,
    EmployeeCarWashListCreateApi,
    EmployeeClockInApi,
    EmployeeClockOutApi,
    EmployeeDailyReportApi,
    EmployeeDashboardApi,
    EmployeeHistoryPointagesApi,
    EmployeeHistoryReportsApi,
    EmployeeHistorySummaryApi,
    EmployeeHistoryWaterApi,
    EmployeeIssueDetailApi,
    EmployeeIssueListCreateApi,
    EmployeePointageStatusApi,
    EmployeeWaterPurchaseApi,
    ManagerCarWashListApi,
    ManagerDashboardApi,
    ManagerIssueListApi,
    ManagerPointageCorrectionApi,
    ManagerPointageDetailApi,
    ManagerPointageListApi,
    ManagerQrDetailApi,
    ManagerQrRegenerateApi,
    PortalSessionApi,
)


urlpatterns = [
    path("session/", PortalSessionApi.as_view(), name="portal_api_session"),
    path("employee/dashboard/", EmployeeDashboardApi.as_view(), name="portal_api_employee_dashboard"),
    path("employee/pointage/", EmployeePointageStatusApi.as_view(), name="portal_api_employee_pointage"),
    path("employee/pointage/clock-in/", EmployeeClockInApi.as_view(), name="portal_api_employee_clock_in"),
    path("employee/pointage/clock-out/", EmployeeClockOutApi.as_view(), name="portal_api_employee_clock_out"),
    path("employee/lavages/", EmployeeCarWashListCreateApi.as_view(), name="portal_api_employee_lavages"),
    path("employee/lavages/<int:lavage_id>/", EmployeeCarWashDetailApi.as_view(), name="portal_api_employee_lavage_detail"),
    path("employee/problemes/", EmployeeIssueListCreateApi.as_view(), name="portal_api_employee_problemes"),
    path("employee/problemes/<int:probleme_id>/", EmployeeIssueDetailApi.as_view(), name="portal_api_employee_probleme_detail"),
    path("employee/rapport-journalier/", EmployeeDailyReportApi.as_view(), name="portal_api_employee_report"),
    path("employee/eau/", EmployeeWaterPurchaseApi.as_view(), name="portal_api_employee_water"),
    path("employee/history/summary/", EmployeeHistorySummaryApi.as_view(), name="portal_api_employee_history_summary"),
    path("employee/history/pointages/", EmployeeHistoryPointagesApi.as_view(), name="portal_api_employee_history_pointages"),
    path("employee/history/reports/", EmployeeHistoryReportsApi.as_view(), name="portal_api_employee_history_reports"),
    path("employee/history/eau/", EmployeeHistoryWaterApi.as_view(), name="portal_api_employee_history_water"),
    path("manager/dashboard/", ManagerDashboardApi.as_view(), name="portal_api_manager_dashboard"),
    path("manager/pointages/", ManagerPointageListApi.as_view(), name="portal_api_manager_pointages"),
    path("manager/pointages/<int:pointage_id>/", ManagerPointageDetailApi.as_view(), name="portal_api_manager_pointage_detail"),
    path("manager/pointages/<int:pointage_id>/correction/", ManagerPointageCorrectionApi.as_view(), name="portal_api_manager_pointage_correction"),
    path("manager/lavages/", ManagerCarWashListApi.as_view(), name="portal_api_manager_lavages"),
    path("manager/problemes/", ManagerIssueListApi.as_view(), name="portal_api_manager_problemes"),
    path("manager/qr/<uuid:site_id>/", ManagerQrDetailApi.as_view(), name="portal_api_manager_qr_detail"),
    path("manager/qr/<uuid:site_id>/regenerate/", ManagerQrRegenerateApi.as_view(), name="portal_api_manager_qr_regenerate"),
]
