from django.urls import path

from .views import (
    EmployeeCarWashDetailApi,
    EmployeeCarWashListCreateApi,
    EmployeeClockInApi,
    EmployeeClockOutApi,
    EmployeeDailyReportApi,
    EmployeeDashboardApi,
    EmployeeFuelPurchaseApi,
    EmployeeHistoryFuelApi,
    EmployeeHistoryPointagesApi,
    EmployeeHistoryReportsApi,
    EmployeeHistorySummaryApi,
    EmployeeHistoryWaterApi,
    EmployeeIssueDetailApi,
    EmployeeIssueListCreateApi,
    EmployeePointageStatusApi,
    EmployeeWaterPurchaseApi,
    ManagerCarWashListApi,
    ManagerDailyReportApi,
    ManagerDashboardApi,
    ManagerFuelPurchaseApi,
    ManagerIssueListApi,
    ManagerManualApi,
    ManagerPointageCorrectionApi,
    ManagerPointageDetailApi,
    ManagerPointageListApi,
    ManagerQrDetailApi,
    ManagerQrRegenerateApi,
    ManagerTeamAttendanceApi,
    ManagerWaterPurchaseApi,
    PortalSessionApi,
)


urlpatterns = [
    path("session/", PortalSessionApi.as_view(), name="portal_api_session"),
    path("employee/dashboard/", EmployeeDashboardApi.as_view(), name="portal_api_employee_dashboard"),
    path("employee/pointage/", EmployeePointageStatusApi.as_view(), name="portal_api_employee_pointage"),
    path("employee/pointage/clock-in/", EmployeeClockInApi.as_view(), name="portal_api_employee_clock_in"),
    path("employee/pointage/clock-out/", EmployeeClockOutApi.as_view(), name="portal_api_employee_clock_out"),
    path("employee/lavages/", EmployeeCarWashListCreateApi.as_view(), name="portal_api_employee_lavages"),
    path("employee/lavages/<int:lavage_id>/", EmployeeCarWashDetailApi.as_view(), name="portal_api_employee_lavage_detail"),
    path("employee/problemes/", EmployeeIssueListCreateApi.as_view(), name="portal_api_employee_problemes"),
    path("employee/problemes/<int:probleme_id>/", EmployeeIssueDetailApi.as_view(), name="portal_api_employee_probleme_detail"),
    path("employee/rapport-journalier/", EmployeeDailyReportApi.as_view(), name="portal_api_employee_report"),
    path("employee/eau/", EmployeeWaterPurchaseApi.as_view(), name="portal_api_employee_water"),
    path("employee/carburant/", EmployeeFuelPurchaseApi.as_view(), name="portal_api_employee_fuel"),
    path("employee/history/summary/", EmployeeHistorySummaryApi.as_view(), name="portal_api_employee_history_summary"),
    path("employee/history/pointages/", EmployeeHistoryPointagesApi.as_view(), name="portal_api_employee_history_pointages"),
    path("employee/history/reports/", EmployeeHistoryReportsApi.as_view(), name="portal_api_employee_history_reports"),
    path("employee/history/eau/", EmployeeHistoryWaterApi.as_view(), name="portal_api_employee_history_water"),
    path("employee/history/carburant/", EmployeeHistoryFuelApi.as_view(), name="portal_api_employee_history_fuel"),
    path("manager/dashboard/", ManagerDashboardApi.as_view(), name="portal_api_manager_dashboard"),
    path("manager/manuel/", ManagerManualApi.as_view(), name="portal_api_manager_manual"),
    path("manager/presence/", EmployeePointageStatusApi.as_view(), name="portal_api_manager_presence"),
    path("manager/presence/clock-in/", EmployeeClockInApi.as_view(), name="portal_api_manager_clock_in"),
    path("manager/presence/clock-out/", EmployeeClockOutApi.as_view(), name="portal_api_manager_clock_out"),
    path("manager/rapport-journalier/", ManagerDailyReportApi.as_view(), name="portal_api_manager_report"),
    path("manager/pointages/", ManagerPointageListApi.as_view(), name="portal_api_manager_pointages"),
    path("manager/pointages/team-attendance/", ManagerTeamAttendanceApi.as_view(), name="portal_api_manager_team_attendance"),
    path("manager/pointages/<int:pointage_id>/", ManagerPointageDetailApi.as_view(), name="portal_api_manager_pointage_detail"),
    path("manager/pointages/<int:pointage_id>/correction/", ManagerPointageCorrectionApi.as_view(), name="portal_api_manager_pointage_correction"),
    path("manager/lavages/", ManagerCarWashListApi.as_view(), name="portal_api_manager_lavages"),
    path("manager/eau/", ManagerWaterPurchaseApi.as_view(), name="portal_api_manager_water"),
    path("manager/carburant/", ManagerFuelPurchaseApi.as_view(), name="portal_api_manager_fuel"),
    path("manager/problemes/", ManagerIssueListApi.as_view(), name="portal_api_manager_problemes"),
    path("manager/qr/<uuid:site_id>/", ManagerQrDetailApi.as_view(), name="portal_api_manager_qr_detail"),
    path("manager/qr/<uuid:site_id>/regenerate/", ManagerQrRegenerateApi.as_view(), name="portal_api_manager_qr_regenerate"),
]
