# Generated by Django 5.0.6 on 2026-01-27 05:49

import django.db.models.deletion
import problemes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("MATERIEL", "Matériel"),
                            ("EAU", "Eau"),
                            ("CLIENT", "Client"),
                            ("SECURITE", "Sécurité"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=problemes.models.issue_photo_path,
                        verbose_name="Photo (optionnel)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("EN_COURS", "En cours"),
                            ("RESOLU", "Résolu"),
                        ],
                        default="OUVERT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes_resolution",
                    models.TextField(blank=True, verbose_name="Notes de résolution"),
                ),
                (
                    "resolu_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Signalé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problemes_signales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signalé par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problemes_traites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problème Signalé",
                "verbose_name_plural": "Problèmes Signalés",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "statut"], name="problemes_i_site_id_8489d8_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="problemes_i_created_0de8a0_idx"
                    ),
                ],
            },
        ),
    ]
