# Generated by Django 5.0.6 on 2026-02-10 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="gps_actif",
            field=models.BooleanField(
                default=False,
                help_text="Activer la vérification GPS pour ce site",
                verbose_name="GPS actif",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="rayon_autorisé_mètres",
            field=models.IntegerField(
                default=50,
                help_text="Rayon autour du site pour la vérification GPS",
                verbose_name="Rayon autorisé (mètres)",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="site_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token du site",
            ),
        ),
    ]
