# Generated by Django 5.0.6 on 2026-02-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_dailybankdeposit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailybankdeposit",
            new_name="sites_daily_site_id_267216_idx",
            old_name="sites_daily_site_id_idx",
        ),
        migrations.RenameIndex(
            model_name="dailybankdeposit",
            new_name="sites_daily_date_3e6e81_idx",
            old_name="sites_daily_date_idx",
        ),
    ]
