# Generated by Django 5.0.6 on 2026-03-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_sitedocument"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sitedocument",
            new_name="sites_sited_site_id_7c5e63_idx",
            old_name="sites_sited_site_id_idx",
        ),
        migrations.RenameIndex(
            model_name="sitedocument",
            new_name="sites_sited_uploade_a34a41_idx",
            old_name="sites_sited_uploaded_idx",
        ),
    ]
