# Generated by Django 5.0.6 on 2026-03-04 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sites",
            "0006_rename_sites_sited_site_id_idx_sites_sited_site_id_7c5e63_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLossEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSPORT", "Transport"),
                            ("PANNE", "Panne / Réparation"),
                            ("CONSOMMABLE", "Consommables"),
                            ("URGENCE", "Urgence / Incident"),
                            ("RETRAIT_BANQUE", "Retrait banque"),
                            ("AUTRE", "Autre perte"),
                        ],
                        default="AUTRE",
                        max_length=30,
                        verbose_name="Type de perte",
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        choices=[("CAISSE", "Caisse du jour"), ("BANQUE", "Banque")],
                        default="CAISSE",
                        max_length=10,
                        verbose_name="Source des fonds",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant (FC)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_losses_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_entries",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perte du Site",
                "verbose_name_plural": "Pertes du Site",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "date"], name="sites_sitel_site_id_3ec622_idx"
                    ),
                    models.Index(
                        fields=["site", "category"],
                        name="sites_sitel_site_id_7083e0_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="sites_sitel_created_cd09ba_idx"
                    ),
                ],
            },
        ),
    ]
