# Generated by Django 5.0.6 on 2026-04-11 22:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0007_sitelossentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUIVI", "Suivi"),
                            ("INTERVENTION", "Intervention"),
                            ("DEPENSE", "Dépense / avance"),
                            ("INCIDENT", "Incident"),
                            ("AUTRE", "Autre"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "amount_fc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant lié (FC)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_journal_entries_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal du Site",
                "verbose_name_plural": "Journal du Site",
                "ordering": ["-entry_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "entry_date"],
                        name="sites_sitej_site_id_0f80ef_idx",
                    ),
                    models.Index(
                        fields=["site", "category"],
                        name="sites_sitej_site_id_2c5859_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="sites_sitej_created_c6b393_idx"
                    ),
                ],
            },
        ),
    ]
