# Generated by Django 5.0.6 on 2026-04-13 22:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0008_sitejournalentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteWaterPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Date d'achat")),
                (
                    "amount_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("24000"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant (FC)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_water_purchases_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_purchases",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat d'eau du Site",
                "verbose_name_plural": "Achats d'eau du Site",
                "ordering": ["-purchase_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "purchase_date"],
                        name="sites_sitew_site_id_f11081_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="sites_sitew_created_3d92de_idx"
                    ),
                ],
            },
        ),
    ]
