# Generated by Django 5.0.6 on 2026-04-13

import django.db.models
from django.db import migrations, models

import sites.models


def populate_billing_month(apps, schema_editor):
    SiteWaterPurchase = apps.get_model("sites", "SiteWaterPurchase")
    for purchase in SiteWaterPurchase.objects.filter(billing_month__isnull=True):
        purchase.billing_month = purchase.purchase_date.replace(day=1)
        purchase.save(update_fields=["billing_month"])


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0009_sitewaterpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewaterpurchase",
            name="billing_month",
            field=models.DateField(
                blank=True,
                help_text="Le mois à facturer au propriétaire du forage.",
                null=True,
                verbose_name="Mois concerné",
            ),
        ),
        migrations.RunPython(populate_billing_month, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sitewaterpurchase",
            name="billing_month",
            field=models.DateField(
                default=sites.models.current_month_start,
                help_text="Le mois à facturer au propriétaire du forage.",
                verbose_name="Mois concerné",
            ),
        ),
        migrations.AlterModelOptions(
            name="sitewaterpurchase",
            options={
                "ordering": ["-billing_month", "-purchase_date", "-created_at"],
                "verbose_name": "Achat d'eau du Site",
                "verbose_name_plural": "Achats d'eau du Site",
            },
        ),
        migrations.AddIndex(
            model_name="sitewaterpurchase",
            index=models.Index(
                fields=["site", "billing_month"],
                name="sites_sitew_site_id_cc7ae3_idx",
            ),
        ),
    ]
