# Generated by Django 5.0.6 on 2026-04-14 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0010_sitewaterpurchase_billing_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitejournalentry",
            name="reminder_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optionnel. Le système enverra un email de rappel à la date et l'heure choisies.",
                null=True,
                verbose_name="Rappel email prévu pour",
            ),
        ),
        migrations.AddField(
            model_name="sitejournalentry",
            name="reminder_email",
            field=models.EmailField(
                blank=True,
                help_text="Défini automatiquement à partir de l'email de l'administrateur connecté.",
                max_length=254,
                verbose_name="Email de rappel",
            ),
        ),
        migrations.AddField(
            model_name="sitejournalentry",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rappel envoyé le"
            ),
        ),
        migrations.AddIndex(
            model_name="sitejournalentry",
            index=models.Index(
                fields=["reminder_at"], name="sites_sitej_reminde_1fa3e4_idx"
            ),
        ),
    ]
