# Generated by Django 5.0.6 on 2026-05-12 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0011_sitejournalentry_reminder_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailybankdeposit",
            name="is_system_generated",
            field=models.BooleanField(
                default=False, verbose_name="Généré automatiquement"
            ),
        ),
        migrations.AddField(
            model_name="dailybankdeposit",
            name="system_source",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Source système"
            ),
        ),
        migrations.AddField(
            model_name="sitelossentry",
            name="is_system_generated",
            field=models.BooleanField(
                default=False, verbose_name="Généré automatiquement"
            ),
        ),
        migrations.AddField(
            model_name="sitelossentry",
            name="system_source",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Source système"
            ),
        ),
        migrations.AddIndex(
            model_name="dailybankdeposit",
            index=models.Index(
                fields=["is_system_generated", "system_source"],
                name="sites_daily_is_syst_f4dd3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitelossentry",
            index=models.Index(
                fields=["is_system_generated", "system_source"],
                name="sites_sitel_is_syst_0ea0b6_idx",
            ),
        ),
    ]
