# Generated by Django 5.0.6 on 2026-05-21 19:58

import django.db.models.deletion
import sites.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0012_dailybankdeposit_is_system_generated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom de la caméra"),
                ),
                (
                    "camera_number",
                    models.PositiveIntegerField(verbose_name="Numéro de caméra"),
                ),
                (
                    "camera_position",
                    models.CharField(
                        choices=[
                            ("GATE", "Entrée / gate"),
                            ("WORK_AREA", "Zone de travail"),
                            ("TOOLS_AREA", "Zone outils"),
                            ("PAYMENT_AREA", "Zone paiement"),
                            ("OUTSIDE", "Extérieur"),
                        ],
                        default="GATE",
                        max_length=20,
                        verbose_name="Position",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nom de l'application"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifiée le"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caméra",
                "verbose_name_plural": "Caméras",
                "ordering": ["site__nom", "camera_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyCameraReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "cars_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de voitures"
                    ),
                ),
                (
                    "motos_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de motos"
                    ),
                ),
                (
                    "total_vehicles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total véhicules"
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Recette attendue (FC)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "ai_cars_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="AI voitures"
                    ),
                ),
                (
                    "ai_motos_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="AI motos"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score confiance AI",
                    ),
                ),
                (
                    "final_cars_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Voitures finales"
                    ),
                ),
                (
                    "final_motos_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Motos finales"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Revu le"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_camera_reports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_camera_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revu par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_camera_reports",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport caméra quotidien",
                "verbose_name_plural": "Rapports caméra quotidiens",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("CAR_COUNT", "Comptage voitures"),
                            ("EMPLOYEE_WORK", "Travail employé"),
                            ("THEFT_SECURITY", "Sécurité / vol"),
                            ("WATER_TANK", "Réservoir d'eau"),
                            ("GENERATOR_FUEL", "Carburant groupe"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Type de preuve",
                    ),
                ),
                ("clip_date", models.DateField(verbose_name="Date du clip")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Heure début"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Heure fin"),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        upload_to=sites.models.camera_evidence_path,
                        verbose_name="Clip ou capture",
                    ),
                ),
                ("s3_url", models.URLField(blank=True, verbose_name="URL S3")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_evidences",
                        to="sites.camera",
                        verbose_name="Caméra",
                    ),
                ),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_evidences",
                        to="sites.dailycamerareport",
                        verbose_name="Rapport quotidien",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_evidences_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve vidéo",
                "verbose_name_plural": "Preuves vidéo",
                "ordering": ["-clip_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["site", "is_active"], name="sites_camer_site_id_9b33e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["site", "camera_position"],
                name="sites_camer_site_id_6d1a08_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="camera",
            unique_together={("site", "camera_number")},
        ),
        migrations.AddIndex(
            model_name="dailycamerareport",
            index=models.Index(
                fields=["site", "date"], name="sites_daily_site_id_633802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailycamerareport",
            index=models.Index(fields=["-date"], name="sites_daily_date_269577_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailycamerareport",
            unique_together={("site", "date")},
        ),
        migrations.AddIndex(
            model_name="videoevidence",
            index=models.Index(
                fields=["daily_report", "clip_date"],
                name="sites_video_daily_r_c7364c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoevidence",
            index=models.Index(
                fields=["camera", "evidence_type"],
                name="sites_video_camera__b7a550_idx",
            ),
        ),
    ]
