# Generated by Django 5.0.6 on 2026-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0013_camera_dailycamerareport_videoevidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycamerareport",
            name="final_three_wheelers_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Motos finales à 3 pneus"
            ),
        ),
        migrations.AddField(
            model_name="dailycamerareport",
            name="three_wheelers_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de motos à 3 pneus"
            ),
        ),
        migrations.AlterField(
            model_name="dailycamerareport",
            name="final_motos_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Motos finales (2 pneus)"
            ),
        ),
        migrations.AlterField(
            model_name="dailycamerareport",
            name="motos_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de motos (2 pneus)"
            ),
        ),
    ]
