# Generated by Django 5.0.6 on 2026-05-24 22:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0015_watersupplier_sitewaterpurchase_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitewaterpurchase",
            name="amount_fc",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("22000"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant (FC)",
            ),
        ),
    ]
