# Generated by Django 5.0.6 on 2026-05-26 16:36

import django.db.models.deletion
import sites.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0016_alter_sitewaterpurchase_amount_fc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraOperatorDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "cars_count",
                    models.PositiveIntegerField(default=0, verbose_name="Voitures"),
                ),
                (
                    "motos_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Motos 2 roues"
                    ),
                ),
                (
                    "three_wheelers_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Motos 3 roues"
                    ),
                ),
                (
                    "total_vehicles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total véhicules"
                    ),
                ),
                (
                    "screenshots_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Captures véhicule"
                    ),
                ),
                (
                    "time_proof_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Preuves horaires"
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Recette attendue (FC)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de fin de journée"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=False, verbose_name="Rapport final soumis"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soumis le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_operator_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contrôleur caméra",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_operator_reports",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport contrôleur caméra",
                "verbose_name_plural": "Rapports contrôleurs caméra",
                "ordering": ["-date", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CameraObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Voiture"),
                            ("MOTO", "Moto 2 roues"),
                            ("THREE_WHEELER", "Moto 3 roues"),
                        ],
                        default="CAR",
                        max_length=20,
                        verbose_name="Type de véhicule",
                    ),
                ),
                (
                    "observed_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure observée"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_observations",
                        to="sites.camera",
                        verbose_name="Caméra",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sites.cameraoperatordailyreport",
                        verbose_name="Rapport contrôleur caméra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation caméra",
                "verbose_name_plural": "Observations caméra",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CameraObservationEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_kind",
                    models.CharField(
                        choices=[
                            ("SCREENSHOT", "Capture véhicule"),
                            ("TIME_PROOF", "Preuve horaire"),
                        ],
                        default="SCREENSHOT",
                        max_length=20,
                        verbose_name="Type de preuve",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        max_length=255,
                        upload_to=sites.models.camera_observation_evidence_path,
                        verbose_name="Capture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="sites.cameraobservation",
                        verbose_name="Observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve observation caméra",
                "verbose_name_plural": "Preuves observation caméra",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["observation", "evidence_kind"],
                        name="sites_camer_observa_fd7ecb_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cameraoperatordailyreport",
            index=models.Index(
                fields=["site", "date"], name="sites_camer_site_id_e28bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cameraoperatordailyreport",
            index=models.Index(
                fields=["controller", "date"], name="sites_camer_control_3b9cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cameraoperatordailyreport",
            index=models.Index(
                fields=["site", "is_submitted"], name="sites_camer_site_id_4e5436_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cameraoperatordailyreport",
            unique_together={("site", "controller", "date")},
        ),
        migrations.AddIndex(
            model_name="cameraobservation",
            index=models.Index(
                fields=["report", "vehicle_type"], name="sites_camer_report__edb060_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cameraobservation",
            index=models.Index(
                fields=["camera", "created_at"], name="sites_camer_camera__e0d26a_idx"
            ),
        ),
    ]
