# Generated by Django 5.0.6 on 2026-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0017_cameraoperatordailyreport_cameraobservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameraobservation",
            name="plate_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="Plaque"),
        ),
    ]
