# Generated by Django 5.0.6 on 2026-05-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0018_cameraobservation_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraobservation",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_observations",
                to="sites.camera",
                verbose_name="Caméra",
            ),
        ),
    ]
