# Generated by Django 5.0.6 on 2026-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0019_alter_cameraobservation_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewaterpurchase",
            name="reporting_week_date",
            field=models.DateField(
                blank=True,
                help_text="Optionnel: choisissez un jour de la semaine du mois concerne pour y rattacher cet achat.",
                null=True,
                verbose_name="Semaine imputee",
            ),
        ),
    ]
