# Generated by Django 5.0.6 on 2026-06-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0021_sitewaterpurchase_paid_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteFuelPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_month",
                    models.DateField(
                        default=sites.models.current_month_start,
                        help_text="Le mois auquel rattacher cet achat de carburant.",
                        verbose_name="Mois concerné",
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Date d'achat")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_fuel_purchases_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_purchases",
                        to="sites.location",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat de carburant du Site",
                "verbose_name_plural": "Achats de carburant du Site",
                "ordering": ["-billing_month", "-purchase_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["site", "billing_month"], name="sites_sf_site_bill_idx"),
                    models.Index(fields=["site", "purchase_date"], name="sites_sf_site_date_idx"),
                    models.Index(fields=["-created_at"], name="sites_sf_created_idx"),
                ],
            },
        ),
    ]
