# Generated by Django 5.0.6 on 2026-06-29 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0022_sitefuelpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitefuelpurchase",
            name="amount_fc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant (FC)",
            ),
        ),
    ]
