# Generated by Django 5.0.6 on 2026-07-26 16:34

import django.core.validators
import sites.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0023_sitefuelpurchase_amount_fc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerManualMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("purpose", models.TextField(verbose_name="Utilité / rôle")),
                ("maintenance", models.TextField(verbose_name="Maintenance")),
                ("troubleshooting", models.TextField(verbose_name="Dépannage")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=sites.models.manager_manual_machine_image_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "training_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sites.models.manager_manual_machine_video_path,
                        verbose_name="Vidéo de formation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Manuel manager - machine",
                "verbose_name_plural": "Manuel manager - machines",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ManagerManualSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_target_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("130000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Objectif quotidien (FC)",
                    ),
                ),
                (
                    "weekly_target_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("845000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Objectif hebdomadaire (FC)",
                    ),
                ),
                (
                    "monthly_target_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3380000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Objectif mensuel (FC)",
                    ),
                ),
                (
                    "car_price_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20000"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarif voiture (FC)",
                    ),
                ),
                (
                    "two_wheel_price_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2500"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarif moto 2 roues (FC)",
                    ),
                ),
                (
                    "three_wheel_price_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarif moto 3 roues (FC)",
                    ),
                ),
                (
                    "default_fuel_cost_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût carburant par défaut (FC)",
                    ),
                ),
                (
                    "default_water_cost_fc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("22000"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût eau par défaut (FC)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Manuel manager - paramètres",
                "verbose_name_plural": "Manuel manager - paramètres",
            },
        ),
        migrations.CreateModel(
            name="ManagerManualSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EAU", "Eau"),
                            ("CARBURANT", "Carburant"),
                            ("CONSOMMABLE", "Consommables"),
                            ("MAINTENANCE", "Maintenance"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contact"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "service_notes",
                    models.TextField(blank=True, verbose_name="Notes de service"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=sites.models.manager_manual_supplier_image_path,
                        verbose_name="Photo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Manuel manager - fournisseur",
                "verbose_name_plural": "Manuel manager - fournisseurs",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
