# Generated by Django 5.0.6 on 2026-08-09 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0024_managermanualmachine_managermanualsettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sitedocument",
            index=models.Index(
                fields=["site", "-uploaded_at"], name="site_doc_site_uploaded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitedocument",
            index=models.Index(
                fields=["site", "file_type", "-uploaded_at"],
                name="site_doc_type_uploaded_idx",
            ),
        ),
    ]
