# Generated by Django 5.0.6 on 2026-08-15

from django.db import migrations


DEFAULT_MACHINE_CARDS = [
    {
        "name": "Nettoyeur haute pression",
        "purpose": "Laver rapidement l'extérieur des véhicules et enlever la saleté avant finition.",
        "maintenance": "Vérifier le carburant ou l'alimentation, nettoyer le filtre, éviter de tirer le tuyau brutalement et ranger la lance après usage.",
        "troubleshooting": "Si la pression baisse, vérifier l'eau, le filtre, les raccords et le carburant avant de déclarer une panne.",
        "display_order": 10,
    },
    {
        "name": "Aspirateur",
        "purpose": "Nettoyer l'intérieur des voitures, tapis, sièges et zones difficiles.",
        "maintenance": "Vider le bac régulièrement, nettoyer le filtre et garder le câble loin de l'eau.",
        "troubleshooting": "Si l'aspiration diminue, vider le bac, contrôler le filtre et vérifier que le tuyau n'est pas bouché.",
        "display_order": 20,
    },
]


def seed_default_manager_machines(apps, schema_editor):
    ManagerManualMachine = apps.get_model("sites", "ManagerManualMachine")
    if ManagerManualMachine.objects.filter(is_active=True).exists():
        return

    for item in DEFAULT_MACHINE_CARDS:
        ManagerManualMachine.objects.update_or_create(
            name=item["name"],
            defaults={
                "purpose": item["purpose"],
                "maintenance": item["maintenance"],
                "troubleshooting": item["troubleshooting"],
                "display_order": item["display_order"],
                "is_active": True,
            },
        )


def remove_seeded_manager_machines(apps, schema_editor):
    ManagerManualMachine = apps.get_model("sites", "ManagerManualMachine")
    ManagerManualMachine.objects.filter(
        name__in=[item["name"] for item in DEFAULT_MACHINE_CARDS],
        image="",
        training_video="",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0025_sitedocument_site_doc_site_uploaded_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_manager_machines, remove_seeded_manager_machines),
    ]
