# Generated by Django 5.0.6 on 2026-08-16 14:01

import django.db.models.deletion
import sites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0026_seed_default_manager_machines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySecretDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Documents légaux"),
                            ("OWNERSHIP", "Propriété / actionnariat"),
                            ("FINANCE", "Finance stratégique"),
                            ("CONTRACT", "Contrats sensibles"),
                            ("STRATEGY", "Stratégie"),
                            ("SECURITY", "Sécurité"),
                            ("OTHER", "Autre document spécial"),
                        ],
                        default="OTHER",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("IMPORTANT", "Important"),
                            ("CONFIDENTIAL", "Confidentiel"),
                            ("TOP_SECRET", "Top secret"),
                        ],
                        default="TOP_SECRET",
                        max_length=30,
                        verbose_name="Niveau de confidentialité",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        storage=sites.models.CompanySecretDocumentStorage(),
                        upload_to=sites.models.company_secret_document_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_secret_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document confidentiel entreprise",
                "verbose_name_plural": "Documents confidentiels entreprise",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-uploaded_at"],
                        name="secret_doc_cat_up_idx",
                    ),
                    models.Index(
                        fields=["sensitivity", "-uploaded_at"],
                        name="company_secret_level_idx",
                    ),
                    models.Index(
                        fields=["-uploaded_at"], name="company_secret_uploaded_idx"
                    ),
                ],
            },
        ),
    ]
