# Generated by Django 5.0.6 on 2026-08-22 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0027_companysecretdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyMeetingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="Titre")),
                (
                    "meeting_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de la réunion",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=160, verbose_name="Lieu"),
                ),
                (
                    "participants",
                    models.TextField(blank=True, verbose_name="Participants"),
                ),
                ("summary", models.TextField(verbose_name="Résumé de la réunion")),
                (
                    "decisions",
                    models.TextField(blank=True, verbose_name="Décisions prises"),
                ),
                (
                    "action_items",
                    models.TextField(blank=True, verbose_name="Actions à suivre"),
                ),
                (
                    "next_steps",
                    models.TextField(blank=True, verbose_name="Prochaines étapes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_meeting_notes_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_meeting_notes_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernière modification par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résumé de réunion",
                "verbose_name_plural": "Résumés de réunions",
                "ordering": ["-meeting_date", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["-meeting_date"], name="meeting_note_date_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="meeting_note_updated_idx"
                    ),
                ],
            },
        ),
    ]
